name: mobile_attendance
description: Mobile Attendance student app (GPS + IP verified check-in).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  geolocator: ^11.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
